const bootsData = {    
    Boots: {
        name: "Boots",
        ap: 0.0,
        ad: 0.0,
        as: 0.0,
        armor: 0.0,
        ls: 0.0,
        crate: 0.0,
        ah: 0.0,
        ms: 6.0,
        hp: 0.0,
        mr: 0.0,
        hpr: 0.0,
        passive: ""
    },
    NO_BOOTS: {
        name: "[NO BOOTS]",
        ap: 0.0,
        ad: 0.0,
        as: 0.0,
        armor: 0.0,
        ls: 0.0,
        crate: 0.0,
        ah: 0.0,
        ms: 0.0,
        hp: 0.0,
        mr: 0.0,
        hpr: 0.0,
        passive: ""
    },
    Wizard_Shoes: {
        name: "Wizard Shoes",
        ap: 0.0,
        ad: 0.0,
        as: 0.0,
        armor: 0.0,
        ls: 0.0,
        crate: 0.0,
        ah: 5.0,
        ms: 13.0,
        hp: 0.0,
        mr: 0.0,
        hpr: 0.0,
        passive: ""
    },
    Agility_Boots: {
        name: "Agility Boots",
        ap: 0.0,
        ad: 0.0,
        as: 0.25,
        armor: 0.0,
        ls: 0.0,
        crate: 0.0,
        ah: 0.0,
        ms: 13.0,
        hp: 0.0,
        mr: 0.0,
        hpr: 0.0,
        passive: ""
    },
    Swift_Boots: {
        name: "Swift Boots",
        ap: 0.0,
        ad: 0.0,
        as: 0.0,
        armor: 0.0,
        ls: 0.0,
        crate: 0.0,
        ah: 0.0,
        ms: 18.0,
        hp: 0.0,
        mr: 0.0,
        hpr: 0.0,
        passive: ""
    },
    Boots_of_Iron_Warriors: {
        name: "Boots of Iron Warriors",
        ap: 0.0,
        ad: 0.0,
        as: 0.0,
        armor: 3.0,
        ls: 0.0,
        crate: 0.0,
        ah: 0.0,
        ms: 10.0,
        hp: 90.0,
        mr: 0.0,
        hpr: 0.0,
        passive: ""
    }
}

export default bootsData;