const heroAbilities = {
  Kumihu: {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 0.33,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 3,
    },
    K: {
      baseAD: 0,
      baseAP: 50,
      scalingAD: 0,
      scalingAP: 0.70,
      perLevelAP: 1.5,
      perLevelAD: 0,
      hits: 2,
    },
    Charm: {
      baseAD: 0,
      baseAP: 80,
      scalingAD: 0,
      scalingAP: 1.1,
      perLevelAP: 2.5, 
      perLevelAD: 0,
      hits: 1,
    }
  },
  Sparrow:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    K: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 0.5,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    L: {
      baseAD: 0,
      baseAP: 50,
      scalingAD: 0,
      scalingAP: 0,
      perLevelAP: 0, 
      perLevelAD: 0,
      hits: 1,
    },
    enh_J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1.1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
  },
  Belle:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    K: {
      baseAD: 0,
      baseAP: 50,
      scalingAD: 0,
      scalingAP: 0.65,
      perLevelAP: 1.5,
      perLevelAD: 0,
      hits: 2,
    },
    L: {
      baseAD: 0,
      baseAP: 45,
      scalingAD: 0,
      scalingAP: 0.6,
      perLevelAP: 1.5, 
      perLevelAD: 0,
      hits: 3,
    },
  },
  ICeat:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    K: {
      baseAD: 0,
      baseAP: 50,
      scalingAD: 0,
      scalingAP: 0.65,
      perLevelAP: 1.5,
      perLevelAD: 0,
      hits: 3,
    },
    L: {
      baseAD: 0,
      baseAP: 40,
      scalingAD: 0,
      scalingAP: 1,
      perLevelAP: 1.5, 
      perLevelAD: 0,
      hits: 11,
    },
  },
  Thomas:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    K: {
      baseAD: 6,
      baseAP: 0,
      scalingAD: 0.2,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0.5,
      hits: 6,
    },
    L: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1.2,
      scalingAP: 0,
      perLevelAP: 0, 
      perLevelAD: 0,
      hits: 1,
    },
  },
  Veil:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    K: {
      baseAD: 0,
      baseAP: 60,
      scalingAD: 0,
      scalingAP: 0.9,
      perLevelAP: 2,
      perLevelAD: 0,
      hits: 1,
    },
    L: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0, 
      perLevelAD: 0,
      hits: 1,
    },
    enh_J: {
      baseAD: 0,
      baseAP: 25,
      scalingAD: 1,
      scalingAP: 0.9,
      perLevelAP: 1,
      perLevelAD: 0,
      hits: 1,
    },
    enh_L: {
      baseAD: 0,
      baseAP: 25,
      scalingAD: 1,
      scalingAP: 0.9,
      perLevelAP: 1, 
      perLevelAD: 0,
      hits: 1,
    },
  },
  Flin:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    K: {
      baseAD: 25,
      baseAP: 0,
      scalingAD: 1.2,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 1,
      hits: 1,
    },
    marksman_J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1.1,
      scalingAP: 0,
      perLevelAP: 0, 
      perLevelAD: 0,
      hits: 1,
    },
  },
  Kira:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    K: {
      baseAD: 0,
      baseAP: 28,
      scalingAD: 0,
      scalingAP: 0.26,
      perLevelAP: 0.75,
      perLevelAD: 0,
      hits: 3,
    },
    enh_J: {
      baseAD: 0,
      baseAP: 40.5,
      scalingAD: 0,
      scalingAP: 0.54,
      perLevelAP: 1, 
      perLevelAD: 0,
      hits: 3,
    },
    enh_K: {
      baseAD: 0,
      baseAP: 28,
      scalingAD: 0,
      scalingAP: 0.26,
      perLevelAP: 0.75, 
      perLevelAD: 0,
      hits: 6,
    },
    enh_L: {
      baseAD: 0,
      baseAP: 140,
      scalingAD: 0,
      scalingAP: 2,
      perLevelAP: 4, 
      perLevelAD: 0,
      hits: 1,
    },
  },
  Hazel:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    K: {
      baseAD: 0,
      baseAP: 30,
      scalingAD: 0,
      scalingAP: 0.8,
      perLevelAP: 0.75,
      perLevelAD: 0,
      hits: 1,
    },
    L: {
      baseAD: 1,
      baseAP: 0,
      scalingAD: 1.5,
      scalingAP: 0,
      perLevelAP: 0, 
      perLevelAD: 0.5,
      hits: 1,
    },
  },
  Arel:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    double_J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1.6,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 2,
    },
    L: {
      baseAD: 25,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0, 
      perLevelAD: 1.5,
      hits: 1,
    },
    bomb_Proc: {
      baseAD: 25,
      baseAP: 0,
      scalingAD: 1.1,
      scalingAP: 0,
      perLevelAP: 0, 
      perLevelAD: 1.5,
      hits: 1,
    },
  },
  Alvar:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    divine_Mark: {
      baseAD: 20,
      baseAP: 0,
      scalingAD: 0,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    K: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    L: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1.1,
      scalingAP: 0,
      perLevelAP: 0, 
      perLevelAD: 0,
      hits: 1,
    },
  },
  Foxy:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    K: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 0.45,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 7,
    },
    L: {
      baseAD: 30,
      baseAP: 0,
      scalingAD: 1.15,
      scalingAP: 0.5,
      perLevelAP: 0, 
      perLevelAD: 1,
      hits: 1,
    },
  },
  Magdalene:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 1,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    K: {
      baseAD: 0,
      baseAP: 70,
      scalingAD: 0,
      scalingAP: 0.8,
      perLevelAP: 2,
      perLevelAD: 0,
      hits: 1,
    },
    L: {
      baseAD: 0,
      baseAP: 30,
      scalingAD: 0,
      scalingAP: 0.4,
      perLevelAP: 1, 
      perLevelAD: 0,
      hits: 1,
    },
    ghost_Proc: {
      baseAD: 0,
      baseAP: 140,
      scalingAD: 0,
      scalingAP: 1.6,
      perLevelAP: 2, 
      perLevelAD: 0,
      hits: 1,
    }
  },
  Prim:
  {
    J: {
      baseAD: 0,
      baseAP: 0,
      scalingAD: 0.33,
      scalingAP: 0,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 3,
    },
    K: {
      baseAD: 0,
      baseAP: 60,
      scalingAD: 0,
      scalingAP: 0.7,
      perLevelAP: 1.5,
      perLevelAD: 0,
      hits: 1,
    },
    L: {
      baseAD: 0,
      baseAP: 80,
      scalingAD: 0,
      scalingAP: 1.2,
      perLevelAP: 2.5, 
      perLevelAD: 0,
      hits: 1,
    },
  },
  Seer:
  {
    benevolent_J: {
      baseAD: 0,
      baseAP: 4,
      scalingAD: 0.7,
      scalingAP: 0.25,
      perLevelAP: 0,
      perLevelAD: 0,
      hits: 1,
    },
    malevolent_J: {
      baseAD: 0,
      baseAP: 5,
      scalingAD: 1,
      scalingAP: 0.14,
      perLevelAP: 0.4,
      perLevelAD: 0,
      hits: 1,
    },
    benevolent_K: {
      baseAD: 0,
      baseAP: 50,
      scalingAD: 0,
      scalingAP: 0.85,
      perLevelAP: 1.5,
      perLevelAD: 0,
      hits: 1,
    },
    malevolent_K: {
      baseAD: 0,
      baseAP: 70,
      scalingAD: 0,
      scalingAP: 0.75,
      perLevelAP: 1.5, 
      perLevelAD: 0,
      hits: 1,
    },
  },
}

export default heroAbilities;
